services:
    database:
        volumes:
            - database:/var/lib/mysql
    app:
        build:
            context: https://github.com/Matht64/BLOC_5.git#main
            dockerfile: Dockerfile
            target: prod
        ports:
            -   40002:80
        depends_on:
            - database
    phpmyadmin:
        ports:
            - 2027:80
        depends_on:
            - database
volumes:
    database:
        driver: local
